import { languages } from '@/app/i18n/settings'
import { cn } from '@/lib/utils'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { App, ConfigProvider } from 'antd'
import ar_EG from 'antd/lib/locale/ar_EG'
import en_US from 'antd/lib/locale/en_US'
import { dir } from 'i18next'
import type { Metadata } from 'next'
import { El_Messiri as FontSans } from 'next/font/google'
import localFont from 'next/font/local'

import { AppProvider } from '@/lib/context'
import { headers } from 'next/headers'

import tenantServiceInstance from '@/lib/services/tenants'
import 'aos/dist/aos.css'
import 'swiper/css/bundle'
import '../globals.css'
import '../mapbox-gl.css'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const dinFont = localFont({
  src: [
    {
      path: '../../../public/fonts/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/meduim.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-din',
})

export const metadata: Metadata = {
  title: 'AtrasLink | أتراس لينك',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode
  params: { lng: string }
}>) {
  const headerList = headers()
  const host = headerList?.get('x-forwarded-host') || headerList?.get('host')
  const tenant =
    host?.split('.')?.[0] &&
    (host?.split('.')?.[0] !== 'atraslink' ||
      host?.split('.')?.[0] !== (process.env.NEXT_PUBLIC_HOST! || 'dashboard'))
      ? host?.split('.')?.[0]
      : undefined
  let result = undefined
  if (
    (!host?.includes('localhost') &&
      !host?.includes('dashboard') &&
      !host?.includes(process.env.NEXT_PUBLIC_HOST!) &&
      host?.includes('.atraslink.com')) ||
    process.env.NEXT_PUBLIC_TENANT_DOMAIN
  ) {
    try {
      let res = await tenantServiceInstance.getTenantByNameVerified(
        host?.includes('localhost') ? process.env.NEXT_PUBLIC_TENANT_DOMAIN! : tenant!
      )
      result = await res.json()
    } catch (e) {
      console.log('Error: ', e)
    }
  }

  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo&family=El+Messiri&family=Playpen+Sans+Arabic&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap"
          rel="stylesheet"
        />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {/*
        {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID && (
          <GoogleAnalytics trackingId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID} />
        )} */}
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyCVPMNg4kqpqdYgDEbWxRDK-P7lx1N7wJQ&language=${lng === 'ar' ? 'ar' : 'en'}&libraries=places&loading=async`}
          defer
        ></script>
      </head>
      <body
        style={
          {
            // Set the CSS variable here
            '--primary-color':
              result?.companyInfo?.primaryColor && result.tenantId
                ? result?.companyInfo?.primaryColor
                : '#07C692',
          } as React.CSSProperties
        }
        suppressHydrationWarning={true}
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          dinFont.variable
        )}
      >
        <AntdRegistry hashPriority="high">
          <ConfigProvider
            i18nIsDynamicList
            theme={{
              components: {
                Button: {
                  colorPrimary:
                    result?.companyInfo?.primaryColor && result.tenantId
                      ? result?.companyInfo?.primaryColor
                      : '#07C692',
                  algorithm: true, // Enable algorithm
                },
              },
              token: {
                colorPrimary:
                  result?.companyInfo?.primaryColor && result.tenantId
                    ? result?.companyInfo?.primaryColor
                    : '#07C692',
                colorLink:
                  result?.companyInfo?.primaryColor && result.tenantId
                    ? result?.companyInfo?.primaryColor
                    : '#07C692',
                colorBgContainer: '#ffffff',
              },
            }}
            locale={lng == 'ar' ? ar_EG : en_US}
            direction={lng === 'ar' ? 'rtl' : 'ltr'}
          >
            <App>
              <AppProvider companyData={result?.companyInfo}>{children}</AppProvider>
            </App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
